CREATE TABLE ANNUAL_LEAVE_APP.PERSONNEL (
	GUID BINARY(16) NOT NULL,
	PERSONNEL_NAME VARCHAR(255) NOT NULL,
	PERSONNEL_DEPARTMENT VARCHAR(255) NOT NULL,
	PERSONNEL_STARTING_DATE	DATE,
	PERSONNEL_WORK_END_DATE DATE,	
	PRIMARY KEY (GUID)
);

CREATE TABLE ANNUAL_LEAVE_APP.LEAVE_TYPES(
	GUID BINARY(16) NOT NULL,
	LEAVE_TYPE VARCHAR(255),
	PRIMARY KEY (GUID)
);

CREATE TABLE ANNUAL_LEAVE_APP.LEAVES(
	GUID BINARY(16) NOT NULL,
	RF_PERSONNEL_GUID BINARY(16) NOT NULL,
	RF_LEAVE_TYPE_GUID BINARY(16) NOT NULL,
	LEAVE_START_DATE DATE NOT NULL,
	LEAVE_END_DATE DATE NOT NULL,
	PRIMARY KEY (GUID)
);

ALTER TABLE ANNUAL_LEAVE_APP.LEAVES ADD CONSTRAINT PERSONNEL_fk0 FOREIGN KEY (RF_PERSONNEL_GUID) REFERENCES ANNUAL_LEAVE_APP.PERSONNEL(GUID);

ALTER TABLE ANNUAL_LEAVE_APP.LEAVES ADD CONSTRAINT LEAVE_TYPES_fk0 FOREIGN KEY (RF_LEAVE_TYPE_GUID) REFERENCES ANNUAL_LEAVE_APP.LEAVE_TYPES(GUID);
