CREATE DATABASE ANNUAL_LEAVE_APP;

CREATE TABLE ANNUAL_LEAVE_APP.PERSONNEL (
	GUID BINARY(16) NOT NULL,
	PERSONNEL_NAME VARCHAR(255) NOT NULL,
	PERSONNEL_DEPARTMENT VARCHAR(255) NOT NULL,
	PERSONNEL_STARTING_DATE	DATE,
	PERSONNEL_WORK_END_DATE DATE,	
	PRIMARY KEY (GUID)
);

CREATE TABLE ANNUAL_LEAVE_APP.LEAVE_TYPES(
	GUID BINARY(16) NOT NULL,
	LEAVE_TYPE VARCHAR(255),
	PRIMARY KEY (GUID)
);

CREATE TABLE ANNUAL_LEAVE_APP.LEAVES(
	GUID BINARY(16) NOT NULL,
	RF_PERSONNEL_GUID BINARY(16) NOT NULL,
	RF_LEAVE_TYPE_GUID BINARY(16) NOT NULL,
	LEAVE_START_DATE DATE NOT NULL,
	LEAVE_END_DATE DATE NOT NULL,
	PRIMARY KEY (GUID)
);

ALTER TABLE ANNUAL_LEAVE_APP.LEAVES ADD CONSTRAINT PERSONNEL_fk0 FOREIGN KEY (RF_PERSONNEL_GUID) REFERENCES ANNUAL_LEAVE_APP.PERSONNEL(GUID);

ALTER TABLE ANNUAL_LEAVE_APP.LEAVES ADD CONSTRAINT LEAVE_TYPES_fk0 FOREIGN KEY (RF_LEAVE_TYPE_GUID) REFERENCES ANNUAL_LEAVE_APP.LEAVE_TYPES(GUID);

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE ANNUAL_LEAVE_APP.`sp_get_all_personnels`()
begin
	select HEX(p.guid) id, 
		   p.PERSONNEL_NAME,
           p.PERSONNEL_DEPARTMENT,
           DATE_FORMAT(p.PERSONNEL_STARTING_DATE,'%d.%m.%Y') START_DATE,
           DATE_FORMAT(p.PERSONNEL_WORK_END_DATE,'%d.%m.%Y') END_DATE
    from ANNUAL_LEAVE_APP.PERSONNEL p;
end$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE ANNUAL_LEAVE_APP.`sp_get_leaves`(
 IN P_RF_PERSONNEL_GUID VARCHAR(50))
begin
	select HEX(a.guid) id, 
		   (select lt.LEAVE_TYPE from ANNUAL_LEAVE_APP.LEAVE_TYPES lt where lt.guid = a.RF_LEAVE_TYPE_GUID) leave_type,
		   a.LEAVE_START_DATE,
           a.LEAVE_END_DATE
    from ANNUAL_LEAVE_APP.LEAVES a 
    where HEX(a.RF_PERSONNEL_GUID) = P_RF_PERSONNEL_GUID;
end$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE ANNUAL_LEAVE_APP.`sp_get_leave_types`()
begin
	select HEX(lt.guid) id, 
    lt.LEAVE_TYPE
    from ANNUAL_LEAVE_APP.LEAVE_TYPES lt;
end$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE ANNUAL_LEAVE_APP.`sp_get_personnel_by_id`(
 IN P_PERSONNEL_GUID VARCHAR(50))
begin
	select HEX(p.guid) id, 
		   p.PERSONNEL_NAME,
           p.PERSONNEL_DEPARTMENT,
           DATE_FORMAT(p.PERSONNEL_STARTING_DATE,'%d.%m.%Y') START_DATE,
           DATE_FORMAT(p.PERSONNEL_WORK_END_DATE,'%d.%m.%Y') END_DATE
    from ANNUAL_LEAVE_APP.PERSONNEL p 
    where HEX(p.GUID) = P_PERSONNEL_GUID;
end$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE ANNUAL_LEAVE_APP.`sp_delete_leave_type_by_id`(
 IN P_LEAVE_TYPE_ID VARCHAR(50))
begin
	delete from annual_leave_app.leave_types where HEX(GUID) = P_LEAVE_TYPE_ID;
end$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE ANNUAL_LEAVE_APP.`sp_delete_personnel_by_id`(
 IN P_PERSONNEL_GUID VARCHAR(50))
begin
	delete from annual_leave_app.personnel where HEX(GUID)= P_PERSONNEL_GUID;
end$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE ANNUAL_LEAVE_APP.`sp_get_personnel_by_name`(
 IN P_PERSONEL_NAME VARCHAR(255))
begin
	select HEX(p.guid) id, 
		   p.PERSONNEL_NAME,
           p.PERSONNEL_DEPARTMENT,
           DATE_FORMAT(p.PERSONNEL_STARTING_DATE,'%d.%m.%Y') START_DATE,
           DATE_FORMAT(p.PERSONNEL_WORK_END_DATE,'%d.%m.%Y') END_DATE
    from ANNUAL_LEAVE_APP.PERSONNEL p 
    where HEX(p.PERSONNEL_NAME) LIKE CONCAT('%', P_PERSONEL_NAME, '%') ;
end$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE ANNUAL_LEAVE_APP.`sp_save_leave_types`(
 IN P_LEAVE_TYPE VARCHAR(255))
begin
	insert into ANNUAL_LEAVE_APP.LEAVE_TYPES(GUID, LEAVE_TYPE) value (unhex(replace(UUID(),'-','')), P_LEAVE_TYPE);
end$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE ANNUAL_LEAVE_APP.`sp_save_leaves`(
 IN P_RF_PERSONNEL_GUID BINARY(16), P_RF_LEAVE_TYPE_GUID BINARY(16), P_LEAVE_START_DATE DATE, P_LEAVE_END_DATE DATE)
begin
	insert into ANNUAL_LEAVE_APP.LEAVES(GUID, RF_PERSONNEL_GUID, RF_LEAVE_TYPE_GUID, LEAVE_START_DATE,
    LEAVE_END_DATE) value (unhex(replace(UUID(),'-','')), P_RF_PERSONNEL_GUID, P_RF_LEAVE_TYPE_GUID, 
    P_LEAVE_START_DATE, P_LEAVE_END_DATE);
end$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE ANNUAL_LEAVE_APP.`sp_save_leaves_types`(
 IN P_LEAVE_TYPE VARCHAR(255))
begin
	insert into ANNUAL_LEAVE_APP.LEAVE_TYPES(GUID, LEAVE_TYPE) value (unhex(replace(UUID(),'-','')), P_LEAVE_TYPE);
end$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE ANNUAL_LEAVE_APP.`sp_save_personnel`(
 IN P_PERSONNEL_NAME VARCHAR(255), IN P_PERSONNEL_DEPARTMENT varchar(255), IN P_PERSONNEL_STARTING_DATE date, 
 P_PERSONNEL_WORK_END_DATE date)
begin
	insert into ANNUAL_LEAVE_APP.PERSONNEL(GUID, PERSONNEL_NAME, PERSONNEL_DEPARTMENT, PERSONNEL_STARTING_DATE,
    PERSONNEL_WORK_END_DATE) value (unhex(replace(UUID(),'-','')), P_PERSONNEL_NAME, P_PERSONNEL_DEPARTMENT, 
    P_PERSONNEL_STARTING_DATE, P_PERSONNEL_WORK_END_DATE);
end$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE ANNUAL_LEAVE_APP.`sp_update_personnel_by_id`(
 IN P_PERSONNEL_GUID VARCHAR(50), IN P_PERSONNEL_NAME VARCHAR(255), IN P_PERSONNEL_DEPARTMENT varchar(255), IN P_PERSONNEL_STARTING_DATE date, 
 P_PERSONNEL_WORK_END_DATE date)
begin
	update annual_leave_app.personnel 
    set 
		personnel_name=P_PERSONNEL_NAME, 
        personnel_department=P_PERSONNEL_DEPARTMENT,
		PERSONNEL_STARTING_DATE=P_PERSONNEL_STARTING_DATE, 
        PERSONNEL_WORK_END_DATE=P_PERSONNEL_WORK_END_DATE 
	where HEX(GUID)=P_PERSONNEL_GUID;
end$$
DELIMITER ;
